version: "3"
services:
  react-app:
    build:
      context: .
      target: dev
    image: react-app
    stdin_open: true
    env_file: .env
    ports: 
      - "3000:3000"
    networks:
      - mern-app
  api-server:
    build:
      context: .
      target: dev
    image: api-server
    ports:
      - "3030:3030"
    # volumes:
    #   - .:/usr/src/app
    #   - node_modules:/usr/src/app/node_modules
    env_file: .env
    environment:
      - MONGO_USERNAME=$MONGO_USERNAME
      - MONGO_PASSWORD=$MONGO_PASSWORD
      - MONGO_HOSTNAME=mongo
      - MONGO_PORT=$MONGO_PORT
      - MONGO_DB=$MONGO_DB
    networks:
      - mern-app
    depends_on:
      - mongo
  mongo:
    image: mongo:latest
    restart: unless-stopped
    env_file: .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
    ports:
      - "27017:27017"
    networks:
      - mern-app
    volumes:
      - mongo-data:/data/db
networks:
  mern-app:
    driver: bridge
volumes:
  mongo-data:
    driver: local
  node_modules: