version: "3"
services:
  react-app:
    container_name: frontend 
    build:
      context: ./frontend/
      target: dev
    image: react-app
    stdin_open: true
    env_file: .env
    environment:
      - WDS_SOCKET_HOST=127.0.0.1
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    ports: 
      - "3000:3000"
    volumes:
      - ./frontend/:/usr/src/app
      - /frontend/usr/src/app/node_modules
    networks:
      - mern-app
  api-server:
    container_name: backend 
    build:
      context: ./backend/
      target: dev
    image: api-server
    ports:
      - "3030:3030"
    volumes:
      - ./backend/:/usr/src/app
      - /backend/usr/src/app/node_modules
    env_file: .env
    environment:
      - CHOKIDAR_USEPOLLING=true
      - MONGO_USERNAME=$MONGO_USERNAME
      - MONGO_PASSWORD=$MONGO_PASSWORD
      - MONGO_HOSTNAME=mongo
      - MONGO_PORT=$MONGO_PORT
      - MONGO_DB=$MONGO_DB
      - REDIS_HOSTNAME=redis
    networks:
      - mern-app
    depends_on:
      - mongo
      - redis
  mongo:
    container_name: mongo 
    image: mongo:latest
    env_file: .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
    ports:
      - "27018:27017"
    networks:
      - mern-app
    volumes:
      - mongo-data:/data/db
  redis:
    container_name: redis 
    image: redis:latest
    ports:
      - '6379:6379'
    networks:
      - mern-app
    volumes:
      - redisDB:/data
networks:
  mern-app:
    driver: bridge
volumes:
  mongo-data:
    driver: local
  redisDB:
    driver: local